modLoader="javafml"
loaderVersion="[30,)"
license="MIT License"
issueTrackerURL="https://github.com/Terrails/StatsKeeper/issues"

[[mods]]
modId="statskeeper"
version="${file.jarVersion}"
displayName="Stats Keeper"

authors="Terrails"
description=''' Saves stats on death & modifies default health '''